title: <p align="center"> Francisco Galán </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/francisco-galan/">LinkedIn</a> |
  <a href="https://github.com/FranciscoGalan">GitHub</a> | 
  <a href="https://public.tableau.com/app/profile/francisco.galan">Tableau Public</a>
  </p>
  
  <p align="left"> <strong> 
  Data Analysis and Visualization Specialist </strong>
  <br>
  <p align="justify">
  I'm currently a Data Visualization Specialist at Improvado, with focus on Tableau, and a Lecturer at the Autonomous Institute of Technology of Mexico.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal