theme: jekyll-theme-minimal
title: Francisco's projects
description: >
  Data Analyst | Technical Communication Specialist
  <br><br>
  <br><br>
  <a href="https://github.com/FranciscoGalan">GitHub Profile</a> | <a href="https://www.linkedin.com/in/francisco-galan/">LinkedIn Profile</a>
