title: <p align="center"> Francisco Galán </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/francisco-galan/">LinkedIn</a> |
  <a href="https://public.tableau.com/app/profile/francisco.galan">Tableau Public</a> | 
  <a href="https://github.com/FranciscoGalan">GitHub</a>
  
  </p>
  
  <p align="left"> <strong> 
  Data Analytics and Visualization Specialist </strong>
  <br>
  <p align="justify">
  I help people make better decisions using data.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal